name: Build and Upload

on:
  workflow_dispatch:  # 允许手动触发工作流程

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  # 指定你需要的Go版本

    - name: Build package
      run: go build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ws_proxy  # 指定包含编译结果的目录
